const msg = {
    success: "Ok",
    Done: "done",
    notFound: "Not Found",
    UsernotExist: "User does not Exist",
    mandatoryPassword: "password is mandatory",
    invalidOtp: "otp is invalid",
    invalidPhone: "Phone Number is invalid",
    invalidReferalCode: "invalid refferal code",
    invalidPassword: "Password is invalid",
    userExist: "User already exists",
    chatExist: "chat already exists",
    isPhoneVerified: "Phone Number is not varified",
    userSignedupWihGoogle: "User is signed up with google.Try to login using google",
    userSignedupWithFacebook: "User is signed up with facebook.Try login using facebook",
    requiredOtp: "otp is required",
    requiredPhone: "Phone Number is required",
    PhoneNumber: "please provide Phone Number",
    timing: "timing not assind",
    unauthorisedRequest: 'Unauthorised request',
    userNotFound: "User not found",
    password_updated: "Password is successfully updated",
    userNotVerified: "User is unverified. Please check your mail to verify",
    loggedIn: "Successfully logIn",
    expireOtp: "otp is expired",
    incorrectOTP: "otp is incorrect",
    invalidAccountNo: "Invalid Account no.",
    duplicatePhone: "Phone number already exists",
    duplicateUnverifiedPhone: "This Phone Id is registered, but not verified",
    invalidCredentials: "Invalid credentials",
    badReq: "Bad request",
    YouDoNotHavePassword: "Please make sure you dont have password you have to forget password",
    serverError: 'Something went wrong, please try again...',
    passwordRequired: "Password required",
    usernameRequired: "Username is Required",
    invalidUsername: "username is invalid",
    resetPassword: 'Reset password link has been send.Please check your email',
    resetPasssuccessful: "password has been successfully updated",
    userDeleted: 'User is successfully deleted',
    NotExist: "Do not exist",
    alreadyViewed: "already viewed",
    NotCreated: "Do not created, try again",
    invalidSender: "invalid sender",
    failedTransaction: "transaction failed",
    actionForbidden: "This action is forbidden. You don't have permission to do this",
    idrequired: "Id is required",
    incorrectPassword: 'Password is Incorrect',
    notPartOfTheConversation: "You are not a part of this Conversation",
    NoTransactionFound: "No Transactions Found",
    NotEnoughAuthority: "You Do Not Have Enough Authority",
    ErrorOccurredWhilePosting: "Some Error occurred! Try posting again",
    ErrorUpdatingPost: "Error ocurred! Try updating again",
    PostNotExist: "Post Does Not Exist"
}

export {msg};